/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registracija;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author user
 */
public class Baza extends javax.swing.JFrame {

    /** Creates new form Baza */
   
    public Baza() {
        initComponents();
        setLocationRelativeTo(null);
        setSize(1070,720);
        show_tabela();
        
        jTable1.setBackground(new Color(0,0,0,0));
        ((DefaultTableCellRenderer)jTable1.getDefaultRenderer(Object.class)).setBackground(new Color(0,0,0,0));
        
        jTable1.setGridColor(new Color(40,87,201));
        jTable1.setForeground(Color.BLACK);
        
        jScrollPane1.setBackground(new Color(0,0,0,0));
        jScrollPane1.setOpaque(false);
        jTable1.setOpaque(false);
        ((DefaultTableCellRenderer)jTable1.getDefaultRenderer(Object.class)).setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        jTable1.setShowGrid(true);
    }
    Update upd=new Update();
     Menu menu= new Menu();
    Connection con=null;
           PreparedStatement ps=null;
           ResultSet rs=null;
           
    public ArrayList<Tabela> tabelaList(){
        ArrayList<Tabela> tabelaList=new ArrayList<>();
        try{
            String q="SELECT VLASNIK.ID, VLASNIK.Ime,VLASNIK.Prezime,VLASNIK.JMBG,VOZILO.Marka,VOZILO.Model,VOZILO.Kubikaza,VOZILO.Snaga,VOZILO.Tablice from VLASNIK INNER JOIN\n" +
"VOZILO ON VLASNIK.JMBG=VOZILO.JMBG;";
            con =DriverManager.getConnection("jdbc:mysql://localhost/registracija","root","");
            ps = con.prepareStatement(q);
             rs=ps.executeQuery();
             Tabela tabela;
             
             while(rs.next()){
                 tabela=new Tabela(rs.getInt("ID"),rs.getString("Ime"),rs.getString("Prezime"),rs.getString("JMBG"),
                         rs.getString("Marka"),rs.getString("Model"),rs.getInt("Kubikaza"),rs.getInt("Snaga"),rs.getString("Tablice"));
                 tabelaList.add(tabela);
                    
             }
             
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        return tabelaList;
    }
    public void show_tabela(){
        ArrayList<Tabela> list=tabelaList();
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        Object[] row=new Object[9];
        for(int i=0;i<list.size();i++){
            row[0]=list.get(i).getID();
            row[1]=list.get(i).getIme();
            row[2]=list.get(i).getPrezime();
            row[3]=list.get(i).getJMBG();
            row[4]=list.get(i).getMarka();
            row[5]=list.get(i).getModel();
            row[6]=list.get(i).getKubikaza();
            row[7]=list.get(i).getSnaga();
            row[8]=list.get(i).getTablice();
            model.addRow(row);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bazaBtn = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1070, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bazaBtn.setBackground(new java.awt.Color(40, 87, 201));
        bazaBtn.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        bazaBtn.setForeground(new java.awt.Color(255, 255, 255));
        bazaBtn.setText("Menu");
        bazaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bazaBtnActionPerformed(evt);
            }
        });
        getContentPane().add(bazaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 110, 60));

        btnDelete.setBackground(new java.awt.Color(40, 87, 201));
        btnDelete.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 13)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 30, 110, 60));

        btnSearch.setBackground(new java.awt.Color(40, 87, 201));
        btnSearch.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 110, 60));

        jTable1.setBackground(new java.awt.Color(102, 204, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Ime", "Prezime", "JMBG", "Marka", "Model", "Kubikaza", "Snaga", "Tablice"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 1050, 540));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\w5.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bazaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bazaBtnActionPerformed
        setVisible(false);
        new Menu().setVisible(true);
       
    }//GEN-LAST:event_bazaBtnActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
       try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/registracija?autoReconnect=true&useSSL=false","root","");
            int row=jTable1.getSelectedRow();
            String value=jTable1.getModel().getValueAt(row, 3).toString();
            int row1=jTable1.getSelectedRow();
            String value1=jTable1.getModel().getValueAt(row, 3).toString();
            String q="DELETE FROM vlasnik where JMBG="+value;
            String q1="DELETE FROM vozilo where JMBG="+value1;
            PreparedStatement pst=con.prepareStatement(q);
            PreparedStatement pst1=con.prepareStatement(q1);
             pst.executeUpdate();
             pst1.executeUpdate();
             DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
              DefaultTableModel model1 = (DefaultTableModel)jTable1.getModel();
              model.setRowCount(0);
            model1.setRowCount(0);
              show_tabela();
            JOptionPane.showMessageDialog(null, "Deleted Successfully!");
           
       }
       catch(Exception  e){
           JOptionPane.showMessageDialog(null,e);
       }
       
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
       new Update().setVisible(true);
     
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Baza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Baza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Baza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Baza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Baza().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bazaBtn;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
