/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registracija;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class Menu extends javax.swing.JFrame {

    /** Creates new form Menu */
   // byte[] slika=null;
    public Menu() {
        initComponents();
        
        setLocationRelativeTo(null);
       // setSize(1006,616);
    
      }
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bazaBtn = new javax.swing.JButton();
        btnRacun = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        panVlasnik = new javax.swing.JPanel();
        lblIme = new javax.swing.JLabel();
        txtPrezime = new javax.swing.JTextField();
        txtAdresa = new javax.swing.JTextField();
        txtIme = new javax.swing.JTextField();
        txtDatRodj = new javax.swing.JTextField();
        txtBrTel = new javax.swing.JTextField();
        txtJMBG = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        lblPrezime = new javax.swing.JLabel();
        lblAdresa = new javax.swing.JLabel();
        lblBrTel = new javax.swing.JLabel();
        lblJMBG = new javax.swing.JLabel();
        lblDatRodj = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtMarka = new javax.swing.JTextField();
        txtModel = new javax.swing.JTextField();
        txtKubikaza = new javax.swing.JTextField();
        txtSnaga = new javax.swing.JTextField();
        txtTezina = new javax.swing.JTextField();
        txtBoja = new javax.swing.JTextField();
        txtGorivo = new javax.swing.JTextField();
        txtBrSasije = new javax.swing.JTextField();
        txtTablice = new javax.swing.JTextField();
        txtOsiguranje = new javax.swing.JTextField();
        txtTehPregled = new javax.swing.JTextField();
        txtDatumR = new javax.swing.JTextField();
        txtIstekR = new javax.swing.JTextField();
        lblMarka = new javax.swing.JLabel();
        lblModel = new javax.swing.JLabel();
        lblKubikaza = new javax.swing.JLabel();
        lblSnaga = new javax.swing.JLabel();
        lblTezina = new javax.swing.JLabel();
        lblBoja = new javax.swing.JLabel();
        lblTablice = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblGorivo = new javax.swing.JLabel();
        lblBrSasije = new javax.swing.JLabel();
        lblOsiguranje = new javax.swing.JLabel();
        lblTehPregled = new javax.swing.JLabel();
        lblDatumR = new javax.swing.JLabel();
        lblIstekR = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bazaBtn.setBackground(new java.awt.Color(40, 87, 201));
        bazaBtn.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        bazaBtn.setForeground(new java.awt.Color(255, 255, 255));
        bazaBtn.setText("Baza");
        bazaBtn.setPreferredSize(new java.awt.Dimension(80, 25));
        bazaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bazaBtnActionPerformed(evt);
            }
        });
        getContentPane().add(bazaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 60));

        btnRacun.setBackground(new java.awt.Color(40, 87, 201));
        btnRacun.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        btnRacun.setForeground(new java.awt.Color(255, 255, 255));
        btnRacun.setText("Racun");
        btnRacun.setPreferredSize(new java.awt.Dimension(80, 25));
        btnRacun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRacunActionPerformed(evt);
            }
        });
        getContentPane().add(btnRacun, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 110, 60));

        btnReset.setBackground(new java.awt.Color(40, 87, 201));
        btnReset.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 110, 60));

        exitBtn.setBackground(new java.awt.Color(40, 87, 201));
        exitBtn.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        exitBtn.setForeground(new java.awt.Color(255, 255, 255));
        exitBtn.setText("LOGOUT");
        exitBtn.setMaximumSize(new java.awt.Dimension(69, 25));
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 110, 60));

        btnSave.setBackground(new java.awt.Color(40, 87, 201));
        btnSave.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 110, 60));

        panVlasnik.setBackground(new java.awt.Color(255, 255, 255));

        txtPrezime.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 13)); // NOI18N
        txtPrezime.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(40, 87, 201)));
        txtPrezime.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPrezimeKeyReleased(evt);
            }
        });

        txtAdresa.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 13)); // NOI18N
        txtAdresa.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(40, 87, 201)));
        txtAdresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAdresaKeyReleased(evt);
            }
        });

        txtIme.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 13)); // NOI18N
        txtIme.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(40, 87, 201)));
        txtIme.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtImeKeyReleased(evt);
            }
        });

        txtDatRodj.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 13)); // NOI18N
        txtDatRodj.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(40, 87, 201)));
        txtDatRodj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDatRodjKeyReleased(evt);
            }
        });

        txtBrTel.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 13)); // NOI18N
        txtBrTel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(40, 87, 201)));
        txtBrTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBrTelKeyReleased(evt);
            }
        });

        txtJMBG.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 13)); // NOI18N
        txtJMBG.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(40, 87, 201)));
        txtJMBG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtJMBGKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 13)); // NOI18N
        jLabel4.setText("Ime:");

        jLabel5.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 13)); // NOI18N
        jLabel5.setText("Prezime:");

        jLabel6.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 13)); // NOI18N
        jLabel6.setText("Adresa:");

        jLabel7.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 13)); // NOI18N
        jLabel7.setText("Datum rodjenja:");

        jLabel8.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 13)); // NOI18N
        jLabel8.setText("BR. Telefona:");

        jLabel9.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 13)); // NOI18N
        jLabel9.setText("JMBG:");

        jPanel1.setBackground(new java.awt.Color(40, 87, 201));
        jPanel1.setPreferredSize(new java.awt.Dimension(1031, 60));

        jLabel23.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("VLASNIK");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel23)
                .addContainerGap(905, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panVlasnikLayout = new javax.swing.GroupLayout(panVlasnik);
        panVlasnik.setLayout(panVlasnikLayout);
        panVlasnikLayout.setHorizontalGroup(
            panVlasnikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panVlasnikLayout.createSequentialGroup()
                .addGroup(panVlasnikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panVlasnikLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panVlasnikLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panVlasnikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))))
                .addGap(42, 42, 42)
                .addGroup(panVlasnikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAdresa, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIme, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(panVlasnikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIme)
                    .addComponent(lblPrezime)
                    .addComponent(lblAdresa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panVlasnikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(54, 54, 54)
                .addGroup(panVlasnikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDatRodj)
                    .addComponent(txtJMBG, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtBrTel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(panVlasnikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblBrTel)
                    .addComponent(lblJMBG)
                    .addComponent(lblDatRodj))
                .addGap(50, 50, 50))
            .addGroup(panVlasnikLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panVlasnikLayout.setVerticalGroup(
            panVlasnikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panVlasnikLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(panVlasnikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panVlasnikLayout.createSequentialGroup()
                        .addGroup(panVlasnikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIme))
                        .addGap(18, 18, 18)
                        .addGroup(panVlasnikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPrezime))
                        .addGap(18, 18, 18)
                        .addGroup(panVlasnikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtAdresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAdresa)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panVlasnikLayout.createSequentialGroup()
                        .addGroup(panVlasnikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBrTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBrTel))
                        .addGap(18, 18, 18)
                        .addGroup(panVlasnikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtJMBG, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblJMBG))
                        .addGap(18, 18, 18)
                        .addGroup(panVlasnikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDatRodj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDatRodj)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panVlasnikLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)))
                .addGap(25, 25, 25))
        );

        getContentPane().add(panVlasnik, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 1030, 210));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 13)); // NOI18N
        jLabel10.setText("Marka:");

        jLabel11.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 13)); // NOI18N
        jLabel11.setText("Model:");

        jLabel12.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 13)); // NOI18N
        jLabel12.setText("Kubikaza:");

        jLabel13.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 13)); // NOI18N
        jLabel13.setText("Snaga:");

        jLabel14.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 13)); // NOI18N
        jLabel14.setText("Tezina:");

        jLabel15.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 13)); // NOI18N
        jLabel15.setText("Boja:");

        jLabel16.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 13)); // NOI18N
        jLabel16.setText("Gorivo:");

        jLabel17.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 13)); // NOI18N
        jLabel17.setText("Broj sasije:");

        jLabel18.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 13)); // NOI18N
        jLabel18.setText("Tablice:");

        jLabel19.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 13)); // NOI18N
        jLabel19.setText("Osiguranje:");

        jLabel20.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 13)); // NOI18N
        jLabel20.setText("Tehnicki Pregled:");

        jLabel21.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 13)); // NOI18N
        jLabel21.setText("Datum registracije:");

        jLabel22.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 13)); // NOI18N
        jLabel22.setText("Datum isteka reg:");

        txtMarka.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 13)); // NOI18N
        txtMarka.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(40, 87, 201)));
        txtMarka.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMarkaKeyReleased(evt);
            }
        });

        txtModel.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 13)); // NOI18N
        txtModel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(40, 87, 201)));
        txtModel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtModelKeyReleased(evt);
            }
        });

        txtKubikaza.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 13)); // NOI18N
        txtKubikaza.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(40, 87, 201)));
        txtKubikaza.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKubikazaKeyReleased(evt);
            }
        });

        txtSnaga.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 13)); // NOI18N
        txtSnaga.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(40, 87, 201)));
        txtSnaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSnagaActionPerformed(evt);
            }
        });
        txtSnaga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSnagaKeyReleased(evt);
            }
        });

        txtTezina.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 13)); // NOI18N
        txtTezina.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(40, 87, 201)));
        txtTezina.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTezinaKeyReleased(evt);
            }
        });

        txtBoja.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 13)); // NOI18N
        txtBoja.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(40, 87, 201)));
        txtBoja.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBojaKeyReleased(evt);
            }
        });

        txtGorivo.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 13)); // NOI18N
        txtGorivo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(40, 87, 201)));
        txtGorivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGorivoActionPerformed(evt);
            }
        });
        txtGorivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGorivoKeyReleased(evt);
            }
        });

        txtBrSasije.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 13)); // NOI18N
        txtBrSasije.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(40, 87, 201)));
        txtBrSasije.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBrSasijeKeyReleased(evt);
            }
        });

        txtTablice.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 13)); // NOI18N
        txtTablice.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(40, 87, 201)));
        txtTablice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTabliceKeyReleased(evt);
            }
        });

        txtOsiguranje.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 13)); // NOI18N
        txtOsiguranje.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(40, 87, 201)));
        txtOsiguranje.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtOsiguranjeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtOsiguranjeFocusLost(evt);
            }
        });
        txtOsiguranje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOsiguranjeActionPerformed(evt);
            }
        });
        txtOsiguranje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtOsiguranjeKeyReleased(evt);
            }
        });

        txtTehPregled.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 13)); // NOI18N
        txtTehPregled.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(40, 87, 201)));
        txtTehPregled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTehPregledActionPerformed(evt);
            }
        });
        txtTehPregled.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTehPregledKeyReleased(evt);
            }
        });

        txtDatumR.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 13)); // NOI18N
        txtDatumR.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(40, 87, 201)));
        txtDatumR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDatumRKeyReleased(evt);
            }
        });

        txtIstekR.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 13)); // NOI18N
        txtIstekR.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(40, 87, 201)));
        txtIstekR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIstekRKeyReleased(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(40, 87, 201));
        jPanel3.setForeground(new java.awt.Color(40, 87, 201));
        jPanel3.setPreferredSize(new java.awt.Dimension(405, 55));

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("VOZILO");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(916, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(31, 31, 31)
                        .addComponent(txtKubikaza, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(48, 48, 48)
                        .addComponent(txtSnaga, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(48, 48, 48)
                        .addComponent(txtTezina, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(58, 58, 58)
                        .addComponent(txtBoja, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(42, 42, 42)
                        .addComponent(txtGorivo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMarka, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKubikaza, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblModel)
                    .addComponent(lblMarka, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTezina, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSnaga, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBoja)
                    .addComponent(lblGorivo))
                .addGap(255, 255, 255)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBrSasije, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTablice, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOsiguranje, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTehPregled, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtDatumR, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIstekR, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIstekR)
                    .addComponent(lblDatumR)
                    .addComponent(lblTehPregled)
                    .addComponent(lblOsiguranje)
                    .addComponent(lblTablice)
                    .addComponent(lblBrSasije))
                .addGap(48, 48, 48))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1031, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMarka, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtMarka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel11)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel12))
                                    .addComponent(txtKubikaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblModel)
                                .addGap(18, 18, 18)
                                .addComponent(lblKubikaza, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtSnaga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblSnaga))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel13)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtTezina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblTezina))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel14)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtBoja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblBoja))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel15))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBrSasije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBrSasije))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTablice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTablice))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtOsiguranje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOsiguranje))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTehPregled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTehPregled))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDatumR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDatumR))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIstekR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIstekR)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel20)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel21)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel22)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGorivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(lblGorivo))
                .addGap(43, 43, 43))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 1030, -1));

        btnUpdate.setBackground(new java.awt.Color(40, 87, 201));
        btnUpdate.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 110, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\w5.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents
Connection con=null;
            PreparedStatement ps1=null;
           PreparedStatement ps=null;
           ResultSet rs=null;
           ResultSet rs1=null;
           Racun r=new Racun();
    private void btnRacunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRacunActionPerformed
       
        
        
        String ime=txtIme.getText();
        String prezime=txtPrezime.getText();
        r.jLabel2.setText(ime+" "+prezime);
        
        String marka=txtMarka.getText();
        String model=txtModel.getText();
        r.jLabel4.setText(marka+" "+model);
        
        String tablice=txtTablice.getText();
        r.jLabel7.setText(tablice);
        
        String kubikaza = txtKubikaza.getText();
        String snaga= txtSnaga.getText();
        String osiguranje = txtOsiguranje.getText();
        String tehnicki = txtTehPregled.getText();
        r.jLabel12.setText(kubikaza);
        r.jLabel13.setText(snaga);
        r.jLabel14.setText(osiguranje);
        r.jLabel15.setText(tehnicki);
        if(txtMarka.equals("")||txtModel.equals("")||txtIme.equals("")||txtPrezime.equals("")||txtKubikaza.equals("")||txtSnaga.equals("")||txtOsiguranje.equals("")||txtTehPregled.equals("")){
            JOptionPane.showMessageDialog(null, "Popunite odredjena polja!");
            r.setVisible(false);
        }
        else{
        if(txtOsiguranje.getText().equals("Ne") ){
            r.lblCOsiguranje.setText("2000");
             r.setVisible(true);
        }
        else if(txtOsiguranje.getText().equals("Da")){
            
            r.lblCOsiguranje.setText("0");
             r.setVisible(true);
        }
        else if(txtOsiguranje.getText().equals("da")){
            
            r.lblCOsiguranje.setText("0");
             r.setVisible(true);
        }
            else if(txtOsiguranje.getText().equals("ne")){
            
            r.lblCOsiguranje.setText("2000");
             r.setVisible(true);
        }
        
            else{
           JOptionPane.showMessageDialog(null, "Unesite samo Da/Ne!");
           r.setVisible(false);
        }
        
        
        
      if(Integer.parseInt(snaga)<40 ||Integer.parseInt(snaga)>499 ){
          JOptionPane.showMessageDialog(null, "Snaga je van granica!");
         r.setVisible(false);
       }
             
           int kw=100;
        
        int suma=Integer.parseInt(snaga)*kw;
      
        String snaga1=Integer.toString(suma);
        
        r.lblCSnaga.setText(snaga1);
       r.setVisible(true);
       
        int kub=10;
        
        int suma1=Integer.parseInt(kubikaza)*kub;
      
        String kubikaza1=Integer.toString(suma1);
        
        r.lblCKubikaza.setText(kubikaza1);
        
            
        if(txtTehPregled.getText().equals("Ne") ){
            r.lblCTehnicki.setText("1500");
             r.setVisible(true);
        }
        else if(txtTehPregled.getText().equals("Da")){
            
            r.lblCTehnicki.setText("0");
             r.setVisible(true);
        }
        else if(txtTehPregled.getText().equals("da")){
            
            r.lblCTehnicki.setText("0");
             r.setVisible(true);
        }
            else if(txtTehPregled.getText().equals("ne")){
            
            r.lblCTehnicki.setText("1500");
             r.setVisible(true);
        }
        
            else{
           JOptionPane.showMessageDialog(null, "Unesite samo Da/Ne!");
           r.setVisible(false);
        }
        String os=r.lblCOsiguranje.getText();
        int os1=Integer.parseInt(os);
        
        String teh=r.lblCTehnicki.getText();
        int teh1=Integer.parseInt(teh);
        int racun=Integer.parseInt(kubikaza1)+Integer.parseInt(snaga1)+os1+teh1;
        
        r.lblRacun.setText(Integer.toString(racun));
        
        }
    }//GEN-LAST:event_btnRacunActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        setVisible(false);
      
    new  Reg().setVisible(true);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void bazaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bazaBtnActionPerformed
      new Baza().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_bazaBtnActionPerformed

    private void txtSnagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSnagaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSnagaActionPerformed

    private void txtGorivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGorivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGorivoActionPerformed

    private void txtOsiguranjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOsiguranjeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOsiguranjeActionPerformed

    private void txtTehPregledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTehPregledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTehPregledActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtPrezime.setText("");
        txtAdresa.setText("");
        txtIme.setText("");
        txtJMBG.setText("");
        txtDatRodj.setText("");
        txtBrTel.setText("");
        txtMarka.setText("");
        txtModel.setText("");
        txtKubikaza.setText("");
        txtSnaga.setText("");
        txtGorivo.setText("");
        txtBoja.setText("");
        txtBrSasije.setText("");
        txtTablice.setText("");
        txtOsiguranje.setText("");
        txtTehPregled.setText("");
        txtDatumR.setText("");
        txtIstekR.setText("");
        txtTezina.setText("");
        
             lblIme.setText("");
            lblPrezime.setText("");
            lblAdresa.setText("");
            lblJMBG.setText("");
            lblDatRodj.setText("");
            lblMarka.setText("");
            lblBrTel.setText("");
            lblModel.setText("");
            lblKubikaza.setText("");
            lblSnaga.setText("");
            lblGorivo.setText("");
            lblBoja.setText("");
            lblBrSasije.setText("");
            lblTablice.setText("");
            lblOsiguranje.setText("");
            lblTehPregled.setText("");
            lblDatumR.setText("");
            lblIstekR.setText("");
            lblTezina.setText("");
                         
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
         if(txtAdresa.getText().trim().isEmpty()||txtPrezime.getText().trim().isEmpty()||txtIme.getText().trim().isEmpty()
                ||txtJMBG.getText().trim().isEmpty() ||txtDatRodj.getText().trim().isEmpty() ||txtMarka.getText().trim().isEmpty()
                ||txtBrTel.getText().trim().isEmpty() ||txtModel.getText().trim().isEmpty() ||txtKubikaza.getText().trim().isEmpty()
                ||txtSnaga.getText().trim().isEmpty() ||txtGorivo.getText().trim().isEmpty() ||txtBoja.getText().trim().isEmpty()
                ||txtBrSasije.getText().trim().isEmpty() ||txtTablice.getText().trim().isEmpty() ||txtOsiguranje.getText().trim().isEmpty()
                ||txtTehPregled.getText().trim().isEmpty() ||txtDatumR.getText().trim().isEmpty() ||txtIstekR.getText().trim().isEmpty()
                ||txtTezina.getText().trim().isEmpty())
        {
            lblIme.setText("*");
            lblIme.setForeground(Color.red);
            lblPrezime.setText("*");
            lblPrezime.setForeground(Color.red);
            lblAdresa.setText("*");
           lblAdresa. setForeground(Color.red);
            lblJMBG.setText("*");
           lblJMBG. setForeground(Color.red);
            lblDatRodj.setText("*");
           lblDatRodj. setForeground(Color.red);
            lblMarka.setText("*");
           lblMarka. setForeground(Color.red);
            lblBrTel.setText("*");
           lblBrTel. setForeground(Color.red);
            lblModel.setText("*");
           lblModel. setForeground(Color.red);
            lblKubikaza.setText("*");
           lblKubikaza. setForeground(Color.red);
            lblSnaga.setText("*");
            lblSnaga. setForeground(Color.red);
            lblGorivo.setText("*");
           lblGorivo. setForeground(Color.red);
            lblBoja.setText("*");
           lblBoja. setForeground(Color.red);
            lblBrSasije.setText("*");
           lblBrSasije. setForeground(Color.red);
            lblTablice.setText("*");
            lblTablice.setForeground(Color.red);
            lblOsiguranje.setText("*");
           lblOsiguranje. setForeground(Color.red);
            lblTehPregled.setText("*");
          lblTehPregled.  setForeground(Color.red);
            lblDatumR.setText("*");
           lblDatumR. setForeground(Color.red);
            lblIstekR.setText("*");
          lblIstekR.  setForeground(Color.red);
            lblTezina.setText("*");
            lblTezina. setForeground(Color.red);
            JOptionPane.showMessageDialog(null, "POPUNITE SVA POLJA!","ERROR",JOptionPane.ERROR_MESSAGE);
        }
      
        
        else{
           
        try{
            Class.forName("com.mysql.jdbc.Driver");
            String q="INSERT INTO vlasnik(JMBG, Ime, Prezime, Adresa, DatumRodj, BrTel)VALUES(?,?,?,?,?,?)";
            
            con =DriverManager.getConnection("jdbc:mysql://localhost:3306/registracija?autoReconnect=true&useSSL=false","root","");
            ps = con.prepareStatement(q);
          
            
        ps.setString(1, txtJMBG.getText());
        ps.setString(2, txtIme.getText());
        ps.setString(3, txtPrezime.getText());
        ps.setString(4, txtAdresa.getText());
        ps.setString(5, txtDatRodj.getText()  );
        ps.setString(6, txtBrTel.getText());
       
        
     ps.executeUpdate();
        
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
            
        try{
            Class.forName("com.mysql.jdbc.Driver");
            String q1="INSERT INTO vozilo(BRMOTORA, Marka, Model, Boja, Tezina, Snaga, Kubikaza, Gorivo, Tablice, Osiguranje, TehnickiPregled, datumReg, datumIsteka, JMBG)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            con =DriverManager.getConnection("jdbc:mysql://localhost:3306/registracija?autoReconnect=true&useSSL=false","root","");
            ps1 = con.prepareStatement(q1);
          
           
        ps1.setString(1, txtBrSasije.getText());
        ps1.setString(2, txtMarka.getText());
        ps1.setString(3, txtModel.getText());
        ps1.setString(4, txtBoja.getText());
        ps1.setString(5, txtTezina.getText());
        ps1.setString(6, txtSnaga.getText());
        ps1.setString(7, txtKubikaza.getText());
        ps1.setString(8, txtGorivo.getText());
        ps1.setString(9, txtTablice.getText());
        ps1.setString(10, txtOsiguranje.getText());
        ps1.setString(11, txtTehPregled.getText());
        ps1.setString(12, txtDatumR.getText());
        ps1.setString(13, txtIstekR.getText());
        ps1.setString(14, txtJMBG.getText());
        
         ps1.executeUpdate();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_btnSaveActionPerformed
        }
    private void txtPrezimeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrezimeKeyReleased
        lblIme.setText("");
    }//GEN-LAST:event_txtPrezimeKeyReleased

    private void txtAdresaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAdresaKeyReleased
       lblPrezime.setText("");
    }//GEN-LAST:event_txtAdresaKeyReleased

    private void txtImeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtImeKeyReleased
        lblAdresa.setText("");
    }//GEN-LAST:event_txtImeKeyReleased

    private void txtBrTelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBrTelKeyReleased
       lblBrTel.setText("");
    }//GEN-LAST:event_txtBrTelKeyReleased

    private void txtJMBGKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJMBGKeyReleased
        lblJMBG.setText("");
    }//GEN-LAST:event_txtJMBGKeyReleased

    private void txtDatRodjKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDatRodjKeyReleased
        lblDatRodj.setText("");
    }//GEN-LAST:event_txtDatRodjKeyReleased

    private void txtMarkaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMarkaKeyReleased
      lblMarka.setText("");
    }//GEN-LAST:event_txtMarkaKeyReleased

    private void txtModelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModelKeyReleased
       lblModel.setText("");
    }//GEN-LAST:event_txtModelKeyReleased

    private void txtKubikazaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKubikazaKeyReleased
       lblKubikaza.setText("");
    }//GEN-LAST:event_txtKubikazaKeyReleased

    private void txtSnagaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSnagaKeyReleased
       lblSnaga.setText("");
    }//GEN-LAST:event_txtSnagaKeyReleased

    private void txtTezinaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTezinaKeyReleased
        lblTezina.setText("");
    }//GEN-LAST:event_txtTezinaKeyReleased

    private void txtBojaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBojaKeyReleased
        lblBoja.setText("");
    }//GEN-LAST:event_txtBojaKeyReleased

    private void txtGorivoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGorivoKeyReleased
       lblGorivo.setText("");
    }//GEN-LAST:event_txtGorivoKeyReleased

    private void txtBrSasijeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBrSasijeKeyReleased
        lblBrSasije.setText("");
    }//GEN-LAST:event_txtBrSasijeKeyReleased

    private void txtTabliceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTabliceKeyReleased
       lblTablice.setText("");
    }//GEN-LAST:event_txtTabliceKeyReleased

    private void txtOsiguranjeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOsiguranjeKeyReleased
       lblOsiguranje.setText("");
    }//GEN-LAST:event_txtOsiguranjeKeyReleased

    private void txtTehPregledKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTehPregledKeyReleased
       lblTehPregled.setText("");
    }//GEN-LAST:event_txtTehPregledKeyReleased

    private void txtDatumRKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDatumRKeyReleased
       lblDatumR.setText("");
    }//GEN-LAST:event_txtDatumRKeyReleased

    private void txtIstekRKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIstekRKeyReleased
       lblIstekR.setText("");
    }//GEN-LAST:event_txtIstekRKeyReleased

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
       try{
        Baza b=new Baza();
        Class.forName("com.mysql.jdbc.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/registracija?autoReconnect=true&useSSL=false","root","");
        Connection con1=DriverManager.getConnection("jdbc:mysql://localhost:3306/registracija?autoReconnect=true&useSSL=false","root","");
       
       String value=txtJMBG.getText();
       String query="UPDATE vlasnik SET Ime=?, Prezime=?, Adresa=?, BrTel=?, DatumRodj=?, JMBG=? where JMBG="+value;
            PreparedStatement pst=con.prepareStatement(query);
            pst.setString(1, txtIme.getText());
            pst.setString(2, txtPrezime.getText());
            pst.setString(3, txtAdresa.getText());
            pst.setString(4, txtBrTel.getText());
            pst.setString(5, txtDatRodj.getText());
            pst.setString(6, txtJMBG.getText());
            
            
            String value1=txtJMBG.getText();
       String query1="UPDATE vozilo SET BRMOTORA=?, Marka=?, Model=?, Boja=?, Tezina=?, Snaga=?, Kubikaza=?, Gorivo=?, Tablice=?, Osiguranje=?, TehnickiPregled=?, datumReg=?, datumIsteka=? where JMBG="+value1;
            PreparedStatement ps1=con.prepareStatement(query1);
             ps1.setString(1, txtBrSasije.getText());
        ps1.setString(2, txtMarka.getText());
        ps1.setString(3, txtModel.getText());
        ps1.setString(4, txtBoja.getText());
        ps1.setString(5, txtTezina.getText());
        ps1.setString(6, txtSnaga.getText());
        ps1.setString(7, txtKubikaza.getText());
        ps1.setString(8, txtGorivo.getText());
        ps1.setString(9, txtTablice.getText());
        ps1.setString(10, txtOsiguranje.getText());
        ps1.setString(11, txtTehPregled.getText());
        ps1.setString(12, txtDatumR.getText());
        ps1.setString(13, txtIstekR.getText());
       // ps1.setString(14, txtJMBG.getText());
        pst.executeUpdate();
        ps1.executeUpdate();
            DefaultTableModel model = (DefaultTableModel)b.jTable1.getModel();
            DefaultTableModel model1 = (DefaultTableModel)b.jTable1.getModel();
            model.setRowCount(0);
           
        
            model1.setRowCount(0);
            b.show_tabela();
             JOptionPane.showMessageDialog(null, "Successfully Updated!");
       }
       catch(Exception  e){
           JOptionPane.showMessageDialog(null,e);
       }
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtOsiguranjeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOsiguranjeFocusGained
     
    }//GEN-LAST:event_txtOsiguranjeFocusGained

    private void txtOsiguranjeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOsiguranjeFocusLost
      
        
    }//GEN-LAST:event_txtOsiguranjeFocusLost
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bazaBtn;
    private javax.swing.JButton btnRacun;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblAdresa;
    private javax.swing.JLabel lblBoja;
    private javax.swing.JLabel lblBrSasije;
    private javax.swing.JLabel lblBrTel;
    private javax.swing.JLabel lblDatRodj;
    private javax.swing.JLabel lblDatumR;
    private javax.swing.JLabel lblGorivo;
    private javax.swing.JLabel lblIme;
    private javax.swing.JLabel lblIstekR;
    private javax.swing.JLabel lblJMBG;
    private javax.swing.JLabel lblKubikaza;
    private javax.swing.JLabel lblMarka;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblOsiguranje;
    private javax.swing.JLabel lblPrezime;
    private javax.swing.JLabel lblSnaga;
    private javax.swing.JLabel lblTablice;
    private javax.swing.JLabel lblTehPregled;
    private javax.swing.JLabel lblTezina;
    private javax.swing.JPanel panVlasnik;
    public javax.swing.JTextField txtAdresa;
    public javax.swing.JTextField txtBoja;
    public javax.swing.JTextField txtBrSasije;
    public javax.swing.JTextField txtBrTel;
    public javax.swing.JTextField txtDatRodj;
    public javax.swing.JTextField txtDatumR;
    public javax.swing.JTextField txtGorivo;
    public javax.swing.JTextField txtIme;
    public javax.swing.JTextField txtIstekR;
    public javax.swing.JTextField txtJMBG;
    public javax.swing.JTextField txtKubikaza;
    public javax.swing.JTextField txtMarka;
    public javax.swing.JTextField txtModel;
    public javax.swing.JTextField txtOsiguranje;
    public javax.swing.JTextField txtPrezime;
    public javax.swing.JTextField txtSnaga;
    public javax.swing.JTextField txtTablice;
    public javax.swing.JTextField txtTehPregled;
    public javax.swing.JTextField txtTezina;
    // End of variables declaration//GEN-END:variables
}
