
package registracija;

import java.sql.*;
import java.awt.Color;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
  
public class Reg extends javax.swing.JFrame {

    /** Creates new form  */
    public Reg() {
        initComponents();
        jPanel1.setFocusable(true);
        setLocationRelativeTo(null);
     
passJText.setEchoChar((char)0);
            passJText.setText("Password");
        
           
      
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        loginB = new javax.swing.JButton();
        userJText = new javax.swing.JTextField();
        passJText = new javax.swing.JPasswordField();
        jcbShowPass = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(64, 64, 193));

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 100)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LOGIN");

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\as1.png")); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\sa1.png")); // NOI18N

        loginB.setBackground(new java.awt.Color(255, 255, 255));
        loginB.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        loginB.setForeground(new java.awt.Color(102, 102, 102));
        loginB.setText("LOGIN");
        loginB.setAlignmentX(0.5F);
        loginB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBActionPerformed(evt);
            }
        });

        userJText.setForeground(new java.awt.Color(153, 153, 153));
        userJText.setText("Username");
        userJText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userJTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userJTextFocusLost(evt);
            }
        });
        userJText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userJTextActionPerformed(evt);
            }
        });

        passJText.setForeground(new java.awt.Color(153, 153, 153));
        passJText.setText("Password");
        passJText.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        passJText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passJTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passJTextFocusLost(evt);
            }
        });
        passJText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passJTextActionPerformed(evt);
            }
        });

        jcbShowPass.setBackground(new java.awt.Color(64, 64, 193));
        jcbShowPass.setForeground(new java.awt.Color(255, 255, 255));
        jcbShowPass.setText("Show Password");
        jcbShowPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbShowPassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(92, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbShowPass)
                            .addComponent(userJText)
                            .addComponent(passJText, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(loginB, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(userJText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passJText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbShowPass)
                .addGap(27, 27, 27)
                .addComponent(loginB, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\sdwdw.jpg")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
Connection con=null;
           PreparedStatement ps=null;
           ResultSet rs=null;
           
    private void userJTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userJTextFocusGained
        if(userJText.getText().trim().equals("Username")){
            userJText.setText("");
              userJText.setForeground(Color.black);
        }
       
    }//GEN-LAST:event_userJTextFocusGained

    private void userJTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userJTextFocusLost
        if(userJText.getText().trim().equals("")){
            userJText.setText("Username");
             userJText.setForeground(new Color(153,153,153));
        }
       
    }//GEN-LAST:event_userJTextFocusLost

    private void passJTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passJTextFocusGained
      
        if(passJText.getText().trim().equals("Password")){
        passJText.setText(""); 
        passJText.setEchoChar('*');
            
            passJText.setForeground(Color.black);
        }
         
    }//GEN-LAST:event_passJTextFocusGained

    private void passJTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passJTextFocusLost
      
         if(passJText.getText().trim().equals("")){
             passJText.setEchoChar((char)0);
             passJText.setText("Password");
             passJText.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_passJTextFocusLost

    private void passJTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passJTextActionPerformed
      
    }//GEN-LAST:event_passJTextActionPerformed

    private void jcbShowPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbShowPassActionPerformed
       
        if(jcbShowPass.isSelected()){
            passJText.setEchoChar((char)0);
         
         
        }
        else
        {
            passJText.setEchoChar('*');
        }
    }//GEN-LAST:event_jcbShowPassActionPerformed

    private void loginBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBActionPerformed
        
        try{
            String q="SELECT * FROM login WHERE username=? and pass=?";
            con =DriverManager.getConnection("jdbc:mysql://localhost/registracija","root","");
            ps = con.prepareStatement(q);
            ps.setString(1,userJText.getText());
            ps.setString(2, passJText.getText());
            rs=ps.executeQuery();
            if(rs.next()){
                new  Menu().setVisible(true);
                
                setVisible(false);
                
            }
            else{
              
                // UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel"); 
                JOptionPane.showMessageDialog(null, "Wrong username or password!","ERROR",JOptionPane.ERROR_MESSAGE);
        
            }
        }
        catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_loginBActionPerformed

    private void userJTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userJTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userJTextActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Reg().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox jcbShowPass;
    private javax.swing.JButton loginB;
    private javax.swing.JPasswordField passJText;
    private javax.swing.JTextField userJText;
    // End of variables declaration//GEN-END:variables
}
